const CREATE_MODEL = 1;
const DEPENDS_ON_MODEL = 2;
const CREATE_ROUTE = 3;
const CREATE_MIDDLEWARE = 4;
const DEPENDS_ON_MIDDLEWARE = 5;
module.exports = {
  CREATE_MODEL,
  DEPENDS_ON_MODEL,
  CREATE_ROUTE,
  CREATE_MIDDLEWARE,
  DEPENDS_ON_MIDDLEWARE
};
